apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TEST_COMP_NEW_LEANIX
  title: TEST_COMP_NEW_LEANIX
  description: 'TEST '
  tags: []
  annotations:
    leanix-location: >-
      https://eu-5.leanix.net/CARIADSandbox/factsheet/Application/462a656f-9822-452a-80b2-c924b8413f7d999
spec:
  owner: default/admins
  lifecycle: development
  type: module
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
