apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: System_1_859
  title: System_1_859
  description: System_1_859
  tags: []
spec:
  owner: default/Group_1_859_Name
  type: service
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
