apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TEST_COMP_NEW_LEANIX
  title: TEST_COMP_NEW_LEANIX
  description: 'TEST '
  tags: []
spec:
  owner: default/admins
  lifecycle: development
  type: module
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
