apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DEMO_KT_NAME
  title: DEMO_KT_NAME
  description: DEMO_KT
  tags:
    - data-platform
  links: []
spec:
  type: business-unit
  profile:
    displayName: DEMO_KT
    email: diwakar.singh02@nagarro.com
  children: []
  members:
    - sneha.dole@cognizant.com
    - diwakar.singh02@nagarro.com

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: DEMO_KT_SYSTEM
  title: DEMO_KT_SYSTEM
  description: DEMO_KT_SYSTEM
  tags: []
spec:
  owner: default/DEMO_KT
  type: product
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
