apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Component_1
  title: TESTING NEW VIEWER
  description: TESTING NEW VIEWER
  tags: []
spec:
  owner: TEAM-A
  lifecycle: production
  type: plugin
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
