apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: TEST_SYSTEM_TECHDOC
  title: TEST_SYSTEM_TECHDOC
  description: TEST_SYSTEM_TECHDOC
  tags: []
spec:
  owner: default/TEST_GROUP_KT_DEMO
  type: service
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
