apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TEST_COMP_VALIDATE_NAME
  title: TEST_COMP_VALIDATE_NAME
  description: TEST
  tags: []
spec:
  owner: default/admins
  lifecycle: experimental
  type: library
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
