apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TEST_CONFLUCNE_DOC_PUBLISH
  title: TEST_CONFLUCNE_DOC_PUBLISH
  description: TEST_CONFLUCNE_DOC_PUBLISH
  tags: []
  annotations:
    backstage.io/techdocs-ref: url:https://devstack.vwgroup.com/confluence/spaces/XLRTE/pages/3564424830/Xelerate+IT+Sec+Evidence+Documents

spec:
  owner: default/admins
  lifecycle: production
  type: service
  providesApis: []
  consumesApis: []
  dependsOn: []
  dependencyOf: []
  fullAccess: []
  limitedAccess: []
  blockedAccess: []
