apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: TESTGROUPLINK
  title: TESTGROUPLINK
  description: TESTGROUPLINK
  tags: []
  links:
    - icon: jira
      title: Jira
      url: https://xelerate-dev.apps.mega.cariad.cloud/create-group
spec:
  type: business-unit
  profile:
    displayName: TESTGROUPLINK
    email: diwakar.singh02@nagarro.com
  children: []
  members:
    - diwakar.singh02@nagarro.com
